version = 3.9.4
maxColumn = 120

align.preset = more
align.multiline = true
align.stripMargin = true

continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
docstrings = JavaDoc
lineEndings = preserve
includeCurlyBraceInSelectChains = false
spaces.inImportCurlyBraces = false
optIn.annotationNewlines = true

rewrite.rules = [Imports, RedundantBraces, SortModifiers]
rewrite.imports.sort = original

docstrings.wrap = yes
docstrings.style = Asterisk

newlines.afterInfix = keep
rewrite.rules = [RedundantParens]
trailingCommas = "always"
runner.dialect = scala213
project.layout = StandardConvention

fileOverride {
  "lang:scala-3" {
    runner.dialect = scala3
  }
}

docstrings.wrapMaxColumn = 80
