/*
 *
 *  Copyright 2017-2019 John A. De Goes and the ZIO Contributors
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific Language governing permissions and
 *  limitations under the License.
 *
 */

package zio.http.model

/*
  Language tags used by Content-Language and Accept-Language header fields.
 */
final case class Language(value: String, param: Map[String, String] = Map.empty)

object Language {

  val ab = Language("Abkhazian")
  val aa = Language("Afar")
  val af = Language("Afrikaans")
  val ak = Language("Akan")
  val sq = Language("Albanian")
  val am = Language("Amharic")
  val ar = Language("Arabic")
  val an = Language("Aragonese")
  val hy = Language("Armenian")
  val as = Language("Assamese")
  val av = Language("Avaric")
  val ae = Language("Avestan")
  val ay = Language("Aymara")
  val az = Language("Azerbaijani")
  val bm = Language("Bambara")
  val ba = Language("Bashkir")
  val eu = Language("Basque")
  val be = Language("Belarusian")
  val bn = Language("Bengali")
  val bh = Language("Bihari Languages")
  val bi = Language("Bislama")
  val bs = Language("Bosnian")
  val br = Language("Breton")
  val bg = Language("Bulgarian")
  val my = Language("Burmese")
  val ca = Language("Catalan, Valencian")
  val ch = Language("Chamorro")
  val ce = Language("Chechen")
  val ny = Language("Chichewa, Chewa, Nyanja")
  val zh = Language("Chinese")
  val cv = Language("Chuvash")
  val kw = Language("Cornish")
  val co = Language("Corsican")
  val cr = Language("Cree")
  val hr = Language("Croatian")
  val cs = Language("Czech")
  val da = Language("Danish")
  val dv = Language("Divehi, Dhivehi, Maldivian")
  val nl = Language("Dutch, Flemish")
  val dz = Language("Dzongkha")
  val en = Language("English")
  val eo = Language("Esperanto")
  val et = Language("Estonian")
  val ee = Language("Ewe")
  val fo = Language("Faroese")
  val fj = Language("Fijian")
  val fi = Language("Finnish")
  val fr = Language("French")
  val ff = Language("Fulah")
  val gl = Language("Galician")
  val ka = Language("Georgian")
  val de = Language("German")
  val el = Language("Greek, Modern (1453-)")
  val gn = Language("Guarani")
  val gu = Language("Gujarati")
  val ht = Language("Haitian, Haitian Creole")
  val ha = Language("Hausa")
  val he = Language("Hebrew")
  val hz = Language("Herero")
  val hi = Language("Hindi")
  val ho = Language("Hiri Motu")
  val hu = Language("Hungarian")
  val ia = Language("Interlingua (International Auxiliary Language Association)")
  val id = Language("Indonesian")
  val ie = Language("Interlingue, Occidental")
  val ga = Language("Irish")
  val ig = Language("Igbo")
  val ik = Language("Inupiaq")
  val io = Language("Ido")
  val is = Language("Icelandic")
  val it = Language("Italian")
  val iu = Language("Inuktitut")
  val ja = Language("Japanese")
  val jv = Language("Javanese")
  val kl = Language("Kalaallisut, Greenlandic")
  val kn = Language("Kannada")
  val kr = Language("Kanuri")
  val ks = Language("Kashmiri")
  val kk = Language("Kazakh")
  val km = Language("Central Khmer")
  val ki = Language("Kikuyu, Gikuyu")
  val rw = Language("Kinyarwanda")
  val ky = Language("Kirghiz, Kyrgyz")
  val kv = Language("Komi")
  val kg = Language("Kongo")
  val ko = Language("Korean")
  val ku = Language("Kurdish")
  val kj = Language("Kuanyama, Kwanyama")
  val la = Language("Latin")
  val lb = Language("Luxembourgish, Letzeburgesch")
  val lg = Language("Ganda")
  val li = Language("Limburgan, Limburger, Limburgish")
  val ln = Language("Lingala")
  val lo = Language("Lao")
  val lt = Language("Lithuanian")
  val lu = Language("Luba-Katanga")
  val lv = Language("Latvian")
  val gv = Language("Manx")
  val mk = Language("Macedonian")
  val mg = Language("Malagasy")
  val ms = Language("Malay")
  val ml = Language("Malayalam")
  val mt = Language("Maltese")
  val mi = Language("Maori")
  val mr = Language("Marathi")
  val mh = Language("Marshallese")
  val mn = Language("Mongolian")
  val na = Language("Nauru")
  val nv = Language("Navajo, Navaho")
  val nd = Language("North Ndebele")
  val ne = Language("Nepali")
  val ng = Language("Ndonga")
  val nb = Language("Norwegian Bokmål")
  val nn = Language("Norwegian Nynorsk")
  val no = Language("Norwegian")
  val ii = Language("Sichuan Yi, Nuosu")
  val nr = Language("South Ndebele")
  val oc = Language("Occitan")
  val oj = Language("Ojibwa")
  val cu = Language("Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic")
  val om = Language("Oromo")
  val or = Language("Oriya")
  val os = Language("Ossetian, Ossetic")
  val pa = Language("Punjabi, Panjabi")
  val pi = Language("Pali")
  val fa = Language("Persian")
  val pl = Language("Polish")
  val ps = Language("Pashto, Pushto")
  val pt = Language("Portuguese")
  val qu = Language("Quechua")
  val rm = Language("Romansh")
  val rn = Language("Rundi")
  val ro = Language("Romanian, Moldavian, Moldovan")
  val ru = Language("Russian")
  val sa = Language("Sanskrit")
  val sc = Language("Sardinian")
  val sd = Language("Sindhi")
  val se = Language("Northern Sami")
  val sm = Language("Samoan")
  val sg = Language("Sango")
  val sr = Language("Serbian")
  val gd = Language("Gaelic, Scottish Gaelic")
  val sn = Language("Shona")
  val si = Language("Sinhala, Sinhalese")
  val sk = Language("Slovak")
  val sl = Language("Slovenian")
  val so = Language("Somali")
  val st = Language("Southern Sotho")
  val es = Language("Spanish, Castilian")
  val su = Language("Sundanese")
  val sw = Language("Swahili")
  val ss = Language("Swati")
  val sv = Language("Swedish")
  val ta = Language("Tamil")
  val te = Language("Telugu")
  val tg = Language("Tajik")
  val th = Language("Thai")
  val ti = Language("Tigrinya")
  val bo = Language("Tibetan")
  val tk = Language("Turkmen")
  val tl = Language("Tagalog")
  val tn = Language("Tswana")
  val to = Language("Tonga (Tonga Islands)")
  val tr = Language("Turkish")
  val ts = Language("Tsonga")
  val tt = Language("Tatar")
  val tw = Language("Twi")
  val ty = Language("Tahitian")
  val ug = Language("Uighur, Uyghur")
  val uk = Language("Ukrainian")
  val ur = Language("Urdu")
  val uz = Language("Uzbek")
  val ve = Language("Venda")
  val vi = Language("Vietnamese")
  val vo = Language("Volapük")
  val wa = Language("Walloon")
  val cy = Language("Welsh")
  val wo = Language("Wolof")
  val fy = Language("Western Frisian")
  val xh = Language("Xhosa")
  val yi = Language("Yiddish")
  val yo = Language("Yoruba")
  val za = Language("Zhuang, Chuang")
  val zu = Language("Zulu")

}
