/*
 *
 *  Copyright 2017-2019 John A. De Goes and the ZIO Contributors
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific Language governing permissions and
 *  limitations under the License.
 *
 */

package zio.http.model

/*
  Language tags used by Content-Language and Accept-Language header fields.
 */
final case class Language(final val ue: String, q: Option[QValue] = None)

final object Language {

  final val ab = Language("Abkhazian")
  final val aa = Language("Afar")
  final val af = Language("Afrikaans")
  final val ak = Language("Akan")
  final val sq = Language("Albanian")
  final val am = Language("Amharic")
  final val ar = Language("Arabic")
  final val an = Language("Aragonese")
  final val hy = Language("Armenian")
  final val as = Language("Assamese")
  final val av = Language("Avaric")
  final val ae = Language("Avestan")
  final val ay = Language("Aymara")
  final val az = Language("Azerbaijani")
  final val bm = Language("Bambara")
  final val ba = Language("Bashkir")
  final val eu = Language("Basque")
  final val be = Language("Belarusian")
  final val bn = Language("Bengali")
  final val bh = Language("Bihari Languages")
  final val bi = Language("Bislama")
  final val bs = Language("Bosnian")
  final val br = Language("Breton")
  final val bg = Language("Bulgarian")
  final val my = Language("Burmese")
  final val ca = Language("Catalan, final val encian")
  final val ch = Language("Chamorro")
  final val ce = Language("Chechen")
  final val ny = Language("Chichewa, Chewa, Nyanja")
  final val zh = Language("Chinese")
  final val cv = Language("Chuvash")
  final val kw = Language("Cornish")
  final val co = Language("Corsican")
  final val cr = Language("Cree")
  final val hr = Language("Croatian")
  final val cs = Language("Czech")
  final val da = Language("Danish")
  final val dv = Language("Divehi, Dhivehi, Maldivian")
  final val nl = Language("Dutch, Flemish")
  final val dz = Language("Dzongkha")
  final val en = Language("English")
  final val eo = Language("Esperanto")
  final val et = Language("Estonian")
  final val ee = Language("Ewe")
  final val fo = Language("Faroese")
  final val fj = Language("Fijian")
  final val fi = Language("Finnish")
  final val fr = Language("French")
  final val ff = Language("Fulah")
  final val gl = Language("Galician")
  final val ka = Language("Georgian")
  final val de = Language("German")
  final val el = Language("Greek, Modern (1453-)")
  final val gn = Language("Guarani")
  final val gu = Language("Gujarati")
  final val ht = Language("Haitian, Haitian Creole")
  final val ha = Language("Hausa")
  final val he = Language("Hebrew")
  final val hz = Language("Herero")
  final val hi = Language("Hindi")
  final val ho = Language("Hiri Motu")
  final val hu = Language("Hungarian")
  final val ia = Language("Interlingua (International Auxiliary Language Association)")
  final val id = Language("Indonesian")
  final val ie = Language("Interlingue, Occidental")
  final val ga = Language("Irish")
  final val ig = Language("Igbo")
  final val ik = Language("Inupiaq")
  final val io = Language("Ido")
  final val is = Language("Icelandic")
  final val it = Language("Italian")
  final val iu = Language("Inuktitut")
  final val ja = Language("Japanese")
  final val jv = Language("Javanese")
  final val kl = Language("Kalaallisut, Greenlandic")
  final val kn = Language("Kannada")
  final val kr = Language("Kanuri")
  final val ks = Language("Kashmiri")
  final val kk = Language("Kazakh")
  final val km = Language("Central Khmer")
  final val ki = Language("Kikuyu, Gikuyu")
  final val rw = Language("Kinyarwanda")
  final val ky = Language("Kirghiz, Kyrgyz")
  final val kv = Language("Komi")
  final val kg = Language("Kongo")
  final val ko = Language("Korean")
  final val ku = Language("Kurdish")
  final val kj = Language("Kuanyama, Kwanyama")
  final val la = Language("Latin")
  final val lb = Language("Luxembourgish, Letzeburgesch")
  final val lg = Language("Ganda")
  final val li = Language("Limburgan, Limburger, Limburgish")
  final val ln = Language("Lingala")
  final val lo = Language("Lao")
  final val lt = Language("Lithuanian")
  final val lu = Language("Luba-Katanga")
  final val lv = Language("Latvian")
  final val gv = Language("Manx")
  final val mk = Language("Macedonian")
  final val mg = Language("Malagasy")
  final val ms = Language("Malay")
  final val ml = Language("Malayalam")
  final val mt = Language("Maltese")
  final val mi = Language("Maori")
  final val mr = Language("Marathi")
  final val mh = Language("Marshallese")
  final val mn = Language("Mongolian")
  final val na = Language("Nauru")
  final val nv = Language("Navajo, Navaho")
  final val nd = Language("North Ndebele")
  final val ne = Language("Nepali")
  final val ng = Language("Ndonga")
  final val nb = Language("Norwegian Bokmål")
  final val nn = Language("Norwegian Nynorsk")
  final val no = Language("Norwegian")
  final val ii = Language("Sichuan Yi, Nuosu")
  final val nr = Language("South Ndebele")
  final val oc = Language("Occitan")
  final val oj = Language("Ojibwa")
  final val cu = Language("Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic")
  final val om = Language("Oromo")
  final val or = Language("Oriya")
  final val os = Language("Ossetian, Ossetic")
  final val pa = Language("Punjabi, Panjabi")
  final val pi = Language("Pali")
  final val fa = Language("Persian")
  final val pl = Language("Polish")
  final val ps = Language("Pashto, Pushto")
  final val pt = Language("Portuguese")
  final val qu = Language("Quechua")
  final val rm = Language("Romansh")
  final val rn = Language("Rundi")
  final val ro = Language("Romanian, Moldavian, Moldovan")
  final val ru = Language("Russian")
  final val sa = Language("Sanskrit")
  final val sc = Language("Sardinian")
  final val sd = Language("Sindhi")
  final val se = Language("Northern Sami")
  final val sm = Language("Samoan")
  final val sg = Language("Sango")
  final val sr = Language("Serbian")
  final val gd = Language("Gaelic, Scottish Gaelic")
  final val sn = Language("Shona")
  final val si = Language("Sinhala, Sinhalese")
  final val sk = Language("Slovak")
  final val sl = Language("Slovenian")
  final val so = Language("Somali")
  final val st = Language("Southern Sotho")
  final val es = Language("Spanish, Castilian")
  final val su = Language("Sundanese")
  final val sw = Language("Swahili")
  final val ss = Language("Swati")
  final val sv = Language("Swedish")
  final val ta = Language("Tamil")
  final val te = Language("Telugu")
  final val tg = Language("Tajik")
  final val th = Language("Thai")
  final val ti = Language("Tigrinya")
  final val bo = Language("Tibetan")
  final val tk = Language("Turkmen")
  final val tl = Language("Tagalog")
  final val tn = Language("Tswana")
  final val to = Language("Tonga (Tonga Islands)")
  final val tr = Language("Turkish")
  final val ts = Language("Tsonga")
  final val tt = Language("Tatar")
  final val tw = Language("Twi")
  final val ty = Language("Tahitian")
  final val ug = Language("Uighur, Uyghur")
  final val uk = Language("Ukrainian")
  final val ur = Language("Urdu")
  final val uz = Language("Uzbek")
  final val ve = Language("Venda")
  final val vi = Language("Vietnamese")
  final val vo = Language("Volapük")
  final val wa = Language("Walloon")
  final val cy = Language("Welsh")
  final val wo = Language("Wolof")
  final val fy = Language("Western Frisian")
  final val xh = Language("Xhosa")
  final val yi = Language("Yiddish")
  final val yo = Language("Yoruba")
  final val za = Language("Zhuang, Chuang")
  final val zu = Language("Zulu")

}
