addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix" % "0.9.26")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.4.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.4.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"  % "0.5.1")
addSbtPlugin("io.spray"           % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"      % "2.1.2")
