package zio.web.websockets.internal

import java.nio.ByteBuffer

import zio.{ Chunk, ChunkBuilder, Has, Task, URLayer, ZIO, ZLayer }
import zio.random.Random

object FrameEncoder {

  trait Service {
    def encode(frame: MessageFrame, masked: Boolean): Task[ByteBuffer]
  }

  val live: URLayer[Random, Has[FrameEncoder.Service]] =
    ZLayer.fromService { random =>
      new FrameEncoder.Service {

        override def encode(frame: MessageFrame, masked: Boolean): Task[ByteBuffer] =
          // must be unpredictable, generated by  strong source of entropy
          random.nextBytes(4).flatMap { maskingKey =>
            Task.effect {
              val buf  = ChunkBuilder.make[Byte]()
              val fin  = if (frame.last) 0x80 else 0x00
              val mask = if (masked) 0x80 else 0x00
              val len  = frame.data.length.toLong

              buf.addOne((fin + frame.opcode).toByte)
              buf.addAll(encodeLength(len, mask))
              buf.addAll(encodeData(frame.data, masked, maskingKey))

              ByteBuffer.wrap(buf.result().toArray)
            }
          }

        private def encodeLength(len: Long, mask: Int) =
          if (len < 126) {
            Chunk((len + mask).toByte)
          } else if (len < 65536) {
            Chunk(
              (0x7E + mask).toByte,
              (len >> 8).toByte,
              (len & 0xFF).toByte
            )
          } else {
            Chunk(
              (0x7F + mask).toByte,
              (len >> 56).toByte,
              ((len >> 48) & 0xFF).toByte,
              ((len >> 40) & 0xFF).toByte,
              ((len >> 32) & 0xFF).toByte,
              ((len >> 24) & 0xFF).toByte,
              ((len >> 16) & 0xFF).toByte,
              ((len >> 8) & 0xFF).toByte,
              (len & 0xFF).toByte
            )
          }

        private def encodeData(data: Chunk[Byte], masked: Boolean, maskingKey: Chunk[Byte]) =
          if (masked) {
            val buf = ChunkBuilder.make[Byte]()

            var i = 0

            while (i < data.length) {
              buf.addOne((data(i) ^ maskingKey(i % 4)).toByte)
              i += 1
            }

            maskingKey ++ buf.result()
          } else data
      }
    }

  def encode(frame: MessageFrame, masked: Boolean): ZIO[Has[FrameEncoder.Service], Throwable, ByteBuffer] =
    ZIO.accessM(_.get[FrameEncoder.Service].encode(frame, masked))
}
