/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  faq: ["faq"],

  reference: [
    "reference/overview",
    "reference/server",
    "reference/client",

    // Routing subsection
    {
      type: "category",
      label: "Routing",
      collapsed: false,
      link: {
        type: "generated-index",
        description:
          "How ZIO HTTP matches an incoming request to a handler: routes, route patterns, and path codecs.",
      },
      items: [
        "reference/routing/routes",
        "reference/routing/route_pattern",
        "reference/routing/path_codec",
      ],
    },
    "reference/handler",
    {
      type: "category",
      label: "HTTP Messages",
      collapsed: false,
      link: {
        type: "generated-index",
        description:
          "The data types that model HTTP requests and responses, including headers and bodies.",
      },
      items: [
        "reference/request",
        "reference/response/response",
        "reference/response/status",
        {
          type: "category",
          label: "Headers",
          link: { type: "doc", id: "reference/headers/headers" },
          items: [
            "reference/headers/session/cookies",
            "reference/headers/session/flash",
          ],
        },
        {
          type: "category",
          label: "Message Body",
          link: { type: "doc", id: "reference/body/body" },
          items: [
            "reference/body/form",
            "reference/body/binary_codecs",
            "reference/body/template",
          ],
        },
      ],
    },
    "reference/template",
    {
      type: "category",
      label: "Declarative Endpoints",
      collapsed: false,
      link: { type: "doc", id: "reference/endpoint" },
      items: ["reference/http-codec"],
    },

    // Aspects subsection
    {
      type: "category",
      label: "Aspects",
      link: {
        type: "generated-index",
        description:
          "Cross-cutting concerns in ZIO HTTP: protocol stacks, middleware, and handler aspects.",
      },
      items: [
        "reference/aop/protocol-stack",
        "reference/aop/middleware",
        "reference/aop/handler_aspect",
      ],
    },

    // Contextual Data Types
    {
      type: "category",
      label: "Request-scoped Context",
      link: { type: 'doc', id: "reference/contextual/index" },
      items: [
        "reference/contextual/request-store",
        "reference/contextual/zio-environment",
      ],
    },

    // WebSocket subsection
    {
      type: "category",
      label: "WebSocket",
      link: { type: "doc", id: "reference/socket/socket" },
      items: ["reference/socket/websocketframe"],
    },

    // ZIO HTTP Testkit subsection
    {
      type: "category",
      label: "Testing (Testkit)",
      link: { type: 'doc', id: "reference/zio-http-testkit/index" },
      items: [
        "reference/zio-http-testkit/test-server",
        "reference/zio-http-testkit/test-client",
        "reference/zio-http-testkit/test-channel",
        "reference/zio-http-testkit/http-test-aspect",
        "reference/zio-http-testkit/examples",
      ],
    },

    // Configs subsection
    {
      type: "category",
      label: "Configs",
      link: { type: "doc", id: "reference/configs/introduction" },
      items: [
        "reference/configs/connection-pool",
        "reference/configs/dns-resolver",
        "reference/configs/server",
        "reference/configs/openapi",
        "reference/configs/netty",
      ],
    },
    {
      type: "category",
      label: "Datastar SDK",
      link: { type: "doc", id: "reference/datastar-sdk/index" },
      items: [
        "reference/datastar-sdk/attributes",
        "reference/datastar-sdk/signals",
        "reference/datastar-sdk/server-api",
        "reference/datastar-sdk/examples",
      ],
    },
  ],

  examples: [
    "examples/index",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      link: {
        type: "generated-index",
        description:
          "Minimal examples to get a ZIO HTTP server and client running.",
      },
      items: ["examples/hello-world", "examples/http-client-server"],
    },
    {
      type: "category",
      label: "Servers and Clients",
      link: {
        type: "generated-index",
        description:
          "Configuring servers and clients: TLS and graceful shutdown.",
      },
      items: ["examples/https-client-server", "examples/graceful-shutdown"],
    },
    {
      type: "category",
      label: "Requests and Responses",
      link: {
        type: "generated-index",
        description:
          "Working with request and response payloads, from domain types to multipart form data.",
      },
      items: ["examples/concrete-entity", "examples/multipart-form-data"],
    },
    {
      type: "category",
      label: "Serving Content",
      link: {
        type: "generated-index",
        description: "Serving static files and rendering HTML templates.",
      },
      items: ["examples/serving-static-files", "examples/html-templating"],
    },
    {
      type: "category",
      label: "Declarative Endpoints",
      link: {
        type: "generated-index",
        description:
          "Describing endpoints declaratively, and what that description makes possible: Scala 3 syntax, server-sent events, and generated command-line clients.",
      },
      items: [
        "examples/endpoint",
        "examples/endpoint-scala3",
        "examples/server-sent-events-in-endpoints",
        "examples/cli",
      ],
    },
    {
      type: "category",
      label: "Streaming and WebSockets",
      link: {
        type: "generated-index",
        description:
          "Streaming request and response bodies, and bidirectional communication over WebSockets.",
      },
      items: ["examples/streaming", "examples/websocket"],
    },
    {
      type: "category",
      label: "Middleware and Authentication",
      link: {
        type: "generated-index",
        description:
          "Applying cross-cutting concerns such as CORS handling and authentication.",
      },
      items: ["examples/middleware-cors-handling", "examples/authentication"],
    },
  ],
  guides: [
    "guides/integration-with-zio-config",
    "guides/testing-http-apps",
    {
       type: "category",
       collapsed: false,
       label: "Authentication",
       link: {
         type: "generated-index",
         description:
           "Guides for adding authentication to a ZIO HTTP application, from basic authentication to OAuth and WebAuthn.",
       },
       items: [
          "guides/basic-authentication",
          "guides/cookie-based-authentication",
          "guides/digest-authentication",
          "guides/authentication-with-opaque-bearer-tokens",
          "guides/authentication-with-jwt-bearer-tokens",
          "guides/authentication-with-jwt-bearer-and-refresh-tokens",
          "guides/authentication-with-a-third-party-oauth-provider",
          "guides/passwordless-authentication-with-webauthn",
       ],
     },
     {
        type: "category",
        collapsed: false,
        label: "Datastar",
        link: {
          type: "generated-index",
          description:
            "Guides for building real-time applications with the ZIO HTTP Datastar integration.",
        },
        items: [
           "guides/real-time-chat-with-datastar",
        ],
     },
     {
        type: "category",
        collapsed: false,
        label: "SSL/TLS",
       link: { type: 'doc', id: "guides/securing-communication-with-ssl-tls" },
       items: [
          "guides/implementing-tls-with-self-signed-server-certificate",
          "guides/implementing-tls-with-root-ca-signed-server-certificate",
          "guides/implementing-tls-with-intermediate-ca-signed-server-certificate",
          "guides/implementing-mutual-tls",
       ],
    }

   ],

  sidebar: [
    "index",
    "installation",
    {
      type: "category",
      collapsed: false,
      label: "Concepts",
      link: {
        type: "generated-index",
        description:
          "The core ideas behind ZIO HTTP: servers, clients, routing, request handling, middleware, and endpoints.",
      },
      items: [
        "concepts/server",
        "concepts/client",
        "concepts/routing",
        "concepts/request-handling",
        "concepts/middleware",
        "concepts/endpoint",
        "concepts/dev-mode"
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
