name: automerge
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  pull_request_review:
    types:
      - submitted

  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.ACTIONS_PAT }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "20"
          MERGE_RETRY_SLEEP: "60000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
          MERGE_REQUIRED_APPROVALS: "1"
